name: Training
sorting: a
folder: null
type: Item
_id: FQAUMNkcagdBLURJ
sort: 200000
color: '#671313'
flags: {}
_stats:
  systemId: crucible
  systemVersion: 0.8.6
  coreVersion: '13.350'
  createdTime: null
  modifiedTime: 1762791095324
  lastModifiedBy: AnoypGxxNIMOS0XY
  compendiumSource: null
  duplicateSource: null
  exportSource: null
description: ''
_key: '!folders!FQAUMNkcagdBLURJ'
