type: Item
folder: Ua0XvGOuOJ5KVvlz
name: Training
color: '#352a51'
sorting: a
_id: meNcaEyQoLucHy0I
description: ''
sort: 0
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.351'
  systemId: crucible
  systemVersion: 0.8.6
  lastModifiedBy: AnoypGxxNIMOS0XY
  modifiedTime: 1763154114539
_key: '!folders!meNcaEyQoLucHy0I'
