export const TAXONOMY_CATEGORIES = {
  beast: "TAXONOMY.CATEGORIES.BEAST",
  elemental: "TAXONOMY.CATEGORIES.ELEMENTAL",
  giant: "TAXONOMY.CATEGORIES.GIANT",
  humanoid: "TAXONOMY.CATEGORIES.HUMANOID",
  outsider: "TAXONOMY.CATEGORIES.OUTSIDER",
  undead: "TAXONOMY.CATEGORIES.UNDEAD"
};
